["UI Settings"]
	showHudText = true
	showCompass = true
	# Default: 60
	# Range: 5 ~ 300
	scanDuration = 60

[Scanning]
	#List of block IDs to scan. Click 'Add' in the config menu to add new entries.
	scannableBlocks = ["satisfactory_ore_nodes:iron_node", "satisfactory_ore_nodes:copper_node"]
